const properties = [
  {
    slug: "a-hotel-in-kasol",
    title: "Workcations 111 - Hotel In Kasol",
    titleShort: "Hotel in Kasol",
    type: "hotel",
    location: {
      city: "kasol",
      state: "himachal pradesh",
    },
    minDuration: 2,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    upload: 49.6,
    download: 37.5,
    latlong: "32.0098202, 77.3111799",
    about:
      "An easy accessibility to the market place and a panoramic views of the all embracing and inviting Parvati Valley Himalayas make it an ideal place to unwind and rejuvenate. Located on the bank of Parvati River, this hotel provides an ideal location to unwind and relax in the soothing natural environment.",
    breakfast: 0,
    lunch: 0,
    dinner: 0,
    features: [
      "wifi",
      "power backup",
      "daily meals",
      "well furnished rooms",
      "regular sanitisation",
      "safety guidelines",
      "housekeeping service",
      "parking",
      "caretaker",
      "café",
      "restaurant",
      "room service",
      "bar",
      "indoor games",
      "outdoor sports",
    ],
    houseRules: [
      "Bachelors are allowed",
      "Couple Friendly",
      "Smoking is allowed",
      "Alcohol consumption is allowed within the rooms",
    ],
    inventory: [
      {
        type: "Deluxe Room",
        size: "150",
        view: "mountain view",
        balcony: "-1",
        features: ["-1"],
        image: ["room"],
        max: 4,
        unit: "room",
        ultrashort: [
          {
            sharing: "Single Sharing",
            cost: 2100,
            costFri: 2100,
            costSat: 2100,
            costSun: 2100,
          },
          {
            sharing: "Double Sharing",
            cost: 2800,
            costFri: 2800,
            costSat: 2800,
            costSun: 2800,
          },
          {
            sharing: "Triple Sharing",
            cost: 3800,
            costFri: 3800,
            costSat: 3800,
            costSun: 3800,
          },
        ],
        short: [
          {
            sharing: "Single Sharing",
            cost: 2000,
            costFri: 2000,
            costSat: 2000,
            costSun: 2000,
          },
          {
            sharing: "Double Sharing",
            cost: 2800,
            costFri: 2800,
            costSat: 2800,
            costSun: 2800,
          },
          {
            sharing: "Triple Sharing",
            cost: 3600,
            costFri: 3600,
            costSat: 3600,
            costSun: 3600,
          },
        ],
        normal: [
          {
            sharing: "Single Sharing",
            cost: 2000,
            costFri: 2000,
            costSat: 2000,
            costSun: 2000,
          },
          {
            sharing: "Double Sharing",
            cost: 2700,
            costFri: 2700,
            costSat: 2700,
            costSun: 2700,
          },
          {
            sharing: "Triple Sharing",
            cost: 3500,
            costFri: 3500,
            costSat: 3500,
            costSun: 3500,
          },
        ],
        long: [
          {
            sharing: "Single Sharing",
            cost: 1900,
            costFri: 1900,
            costSat: 1900,
            costSun: 1900,
          },
          {
            sharing: "Double Sharing",
            cost: 2600,
            costFri: 2600,
            costSat: 2600,
            costSun: 2600,
          },
          {
            sharing: "Triple Sharing",
            cost: 3500,
            costFri: 3500,
            costSat: 3500,
            costSun: 3500,
          },
        ],
        ultralong: [
          {
            sharing: "Single Sharing",
            cost: 1800,
            costFri: 1800,
            costSat: 1800,
            costSun: 1800,
          },
          {
            sharing: "Double Sharing",
            cost: 2500,
            costFri: 2500,
            costSat: 2500,
            costSun: 2500,
          },
          {
            sharing: "Triple Sharing",
            cost: 3300,
            costFri: 3300,
            costSat: 3300,
            costSun: 3300,
          },
        ],
      },
      {
        type: "Super Deluxe Room",
        size: "150",
        view: "mountain view",
        balcony: "private balcony",
        features: ["-1"],
        image: ["room"],
        max: 4,
        unit: "room",
        ultrashort: [
          {
            sharing: "Single Sharing",
            cost: 2300,
            costFri: 2300,
            costSat: 2300,
            costSun: 2300,
          },
          {
            sharing: "Double Sharing",
            cost: 3000,
            costFri: 3000,
            costSat: 3000,
            costSun: 3000,
          },
          {
            sharing: "Triple Sharing",
            cost: 4000,
            costFri: 4000,
            costSat: 4000,
            costSun: 4000,
          },
        ],
        short: [
          {
            sharing: "Single Sharing",
            cost: 2200,
            costFri: 2200,
            costSat: 2200,
            costSun: 2200,
          },
          {
            sharing: "Double Sharing",
            cost: 3000,
            costFri: 3000,
            costSat: 3000,
            costSun: 3000,
          },
          {
            sharing: "Triple Sharing",
            cost: 3800,
            costFri: 3800,
            costSat: 3800,
            costSun: 3800,
          },
        ],
        normal: [
          {
            sharing: "Single Sharing",
            cost: 2200,
            costFri: 2200,
            costSat: 2200,
            costSun: 2200,
          },
          {
            sharing: "Double Sharing",
            cost: 2900,
            costFri: 2900,
            costSat: 2900,
            costSun: 2900,
          },
          {
            sharing: "Triple Sharing",
            cost: 3700,
            costFri: 3700,
            costSat: 3700,
            costSun: 3700,
          },
        ],
        long: [
          {
            sharing: "Single Sharing",
            cost: 2100,
            costFri: 2100,
            costSat: 2100,
            costSun: 2100,
          },
          {
            sharing: "Double Sharing",
            cost: 2800,
            costFri: 2800,
            costSat: 2800,
            costSun: 2800,
          },
          {
            sharing: "Triple Sharing",
            cost: 3700,
            costFri: 3700,
            costSat: 3700,
            costSun: 3700,
          },
        ],
        ultralong: [
          {
            sharing: "Single Sharing",
            cost: 2000,
            costFri: 2000,
            costSat: 2000,
            costSun: 2000,
          },
          {
            sharing: "Double Sharing",
            cost: 2700,
            costFri: 2700,
            costSat: 2700,
            costSun: 2700,
          },
          {
            sharing: "Triple Sharing",
            cost: 3500,
            costFri: 3500,
            costSat: 3500,
            costSun: 3500,
          },
        ],
      },
    ],
    images: [
      "entry",
      "room",
      "balcony",
      "balcony-view",
      "dining-area",
      "restaurant",
      "parking",
      "room-sitting-area",
      "room-view",
      "deluxe-room",
      "super-deluxe-room",
      "deluxe-bedroom",
      "bedroom",
      "washroom",
      "hotel-view",
      "outside",
      "dining",
      "reception",
    ],
    inclusions: [],
    exclusions: [
      "Laundry Service",
      "Toiletries",
      "Any Meals outside the set menu",
    ],
    nearby: [
      {
        image: "kheerganga",
        title: "Kheerganga",
        distance: "22",
      },
      {
        image: "manali",
        title: "Manali",
        distance: "78",
      },
      {
        image: "malana-village",
        title: "Malana Village",
        distance: "22",
      },
      {
        image: "tirthan-valley",
        title: "Tirthan Valley",
        distance: "52",
      },
    ],
    essentials: [
      {
        title: "medical",
        distance: "8.8",
      },
      {
        title: "market",
        distance: "0.3",
      },
      {
        title: "atm",
        distance: "1.1",
      },
      {
        title: "petrol",
        distance: "12.4",
      },
    ],
  },
];
